### PR TITLE
picture width

### PR DESCRIPTION
**Pull request by dsavchenko**

### CODE REVIEW

**Comment by volodymyrss** [comment]
that's not really CSS but ok in principle. Maybe @burnout87 or @motame  can suggest which class to set to inherit better from frontend theme? This would be more in-style.

But if there is any trouble with this, let's just move with what you put.

Just one thing, could you please put screenshot for reference?

**Comment by dsavchenko** [comment]
> that's not really CSS but ok in principle

I agree, but the same (even less flexible) approach is used for the bokeh-based plots, e.g. 
https://github.com/oda-hub/dispatcher-app/blob/74e260a4ad87df1c1fcc62a2b43578b82fb4e82d/cdci_data_analysis/analysis/products.py#LL431C19-L431C19
where the size is set in pixels (probably, it's not possible other way with bokeh)

**Comment by volodymyrss** [comment]
> > that's not really CSS but ok in principle
> 
> I agree, but the same (even less flexible) approach is used for the bokeh-based plots, e.g. https://github.com/oda-hub/dispatcher-app/blob/74e260a4ad87df1c1fcc62a2b43578b82fb4e82d/cdci_data_analysis/analysis/products.py#LL431C19-L431C19 where the size is set in pixels (probably, it's not possible other way with bokeh)

Yes and we are also not too happy about that. So if @burnout87 or @motame have an advice it's better. Else let's merge tomorrow?

**Comment by burnout87** [comment]
I haven't looked into it but it can probably added using CSS class on the fronted side. It's important to verify that it does not affect the visualization of other types of images. I will take a look

**Comment by volodymyrss** [comment]
> I haven't looked into it but it can probably be fixed by using CSS class on the fronted side. It's important to verify that it does not affect the visualization of other types of images. I will take a look

Ideally it would be just adding to this img an existing CSS class from frontend, i.e. no change to frontend CSS.

For example,  `img-responsive` from bootstrap.css?

**Comment by dsavchenko** [comment]
> For example, `img-responsive` from bootstrap.css?

I confirm it works.

**Review by volodymyrss — APPROVED** [review]

**Pull request merged**
